### ISSUE TITLE
Review of blog post: Team Team

### ISSUE THREAD

**Issue by HazemSaeid** [mikkelertbjerg/gRPC-vs-REST#2]
| Technical Dimensions / Weight                                | Does Not Meet Expectations (1-3 points)                                                         | Meets Expectations (4-7 points)                                                                             | Exceeds Expectations (8-10 points)                                                                                                          | Score |
|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|-------|
| **Overview 30%**                                             | Fails to provide an overview and define the scope of the work                                   | Provides an adequate overview and general explanation on the scope of the work                              | Provides a thorough overview and thoroughly defines the scope of the work                                                                   |     10  |
| **Reliable Data from Credible Sources 10%**                  | Data not reliable and fails to provide reference to source of data                              | Adequately describes selection of data and provides a general explanation on source of data                 | Provides in-depth explanations on data selection and credible sources with clear and complete references                                    |   7    |
| **Design Constraints and Assumptions 15%**                   | Fails to discuss design constraints and alternatives; provides no justification for assumptions | Adequately explains and justifies the design constraints, design alternatives and assumptions used          | In-depth explanations and justifications are provided on design constraints, alternatives and assumptions used                              |   10    |
| **Theoretical Explanations 20%**                             | Fails to adequately cover theoretical explanations                                              | Adequately addresses theoretical explanations                                                               | Demonstrates in-depth research and analysis                                                                                                 |   10    |
| **Design Criteria, Sample Calculations and Simulations 20%** | Fails to provide appropriate design methodology, relevant sample calculations, and simulations  | Demonstrates adequate level of design criteria and relevant sample calculations and appropriate simulations | Provides in-depth explanations on design criteria, thoroughly discusses all required calculation steps and uses simulations where necessary |   10    |
| **Previous Work / Future Work 5%**                           | Fails to summarize previous work or to discuss future work                                      | Adequately summarizes previous work and discusses potential future work                                     | Provides a thorough summary of previous work and proposes and discusses future work in detail                                                |   7    |
| **Total 100%**                                               |                                                                                           90%      | **Technical / Content Criteria**                                                                            |                                                                                                                                             |    54   |
-   too many unexplained links (especially in the intro). Are they all included down at the references? Maybe use a number reference system for them?
- Maybe show some evidence for why gRPC could be better in multiple programs/services across diffirent languages.
- is fast always superior? how about stability, implementation etc.
- Most sources are reliable, however some aren't that relevant to the problem statement. Why go into design by contract, serilization, loading time for websites etc.
- (small note) is the "setup" of the project necessary in the blog entry?

**Comment by mikkelertbjerg** [comment]
- A reference system has been added to the blog
- Showing concrete evidence to why gRPC is better in other programs is out of scope for this blog, and should be covered in the referenced articles.
- Fast is not always superior, but this blog is about speed and nothing else. Adjustments has been made to put emphasis on this point. A "What's next" section has also been added to clarify this.
- We're going into what gRPC is and some of the features briefly touched on, are to give the reader and good idea of what gRPC is and what attribute to its proclaimed speed.
- Yes, the setup is totally nescessary :-)
